const ConfigurationActionTypes = {
    ADD_CONFIGURATION: 'ADD_CONFIGURATION',
    EDIT_CONFIGURATION: 'EDIT_CONFIGURATION',
    DELETE_CONFIGURATION: 'DELETE_CONFIGURATION',
    FETCH_CONFIGURATION: 'FETCH_CONFIGURATION',
    RECEIVE_CONFIGURATION: 'RECEIVE_CONFIGURATION'
}

export default ConfigurationActionTypes;