const TimerActionTypes = {
    START_TIMER: 'START_TIMER',
    STOP_TIMER: 'STOP_TIMER',
    RESET_TIMER: 'RESET_TIMER',
    SET_TASK_TIMER: 'SET_TASK_TIMER',
    COMPLETE_TASK: 'COMPLETE_TASK',
    SET_TOTAL_TIME: 'SET_TOTAL_TIME',
    SET_DEFAULT: 'SET_DEFAULT'
}

export default TimerActionTypes;